### PR TITLE
Prepare for v0.5.0

### PR DESCRIPTION
**Pull request by utam0k**

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey, 
1. I think we need to bump to 0.5.0 as there is atleast one breaking change, see https://github.com/youki-dev/youki/pull/2906
2. If you can wait till tom, I will review the test part of the preserve fd PR today, and get it merged unless there are major changes required, so it can go in this release as well.

**Comment by utam0k** [comment]
> Hey,
> 
> 1. I think we need to bump to 0.5.0 as there is atleast one breaking change, see [Release for v0.4.2 #2906](https://github.com/youki-dev/youki/pull/2906)
> 2. If you can wait till tom, I will review the test part of the preserve fd PR today, and get it merged unless there are major changes required, so it can go in this release as well.

Make sense.

**Review by YJDoc2 — COMMENTED** [review]
Hey, you have to update the version to 0.5.0 in the code. Also I have approved the preserve-fd PR, left a comment without merging, please take a look and we can merge.

**Comment by utam0k** [comment]
@YJDoc2 I think we are ready to release the new version! PTAL 🙏

**Review by YJDoc2 — APPROVED** [review]
Thanks!

**Pull request merged**
